// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.NumbertoWords
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("number")]
        public double Number { get; set; }

        [JsonProperty("words")]
        public string Words { get; set; }

        [JsonProperty("ordinal")]
        public string Ordinal { get; set; }

        [JsonProperty("numberOfDigits_numeric")]
        public long NumberOfDigitsNumeric { get; set; }

        [JsonProperty("numberOfDigits_words")]
        public string NumberOfDigitsWords { get; set; }

        [JsonProperty("eachNumber")]
        public string[] EachNumber { get; set; }

        [JsonProperty("afterDecimal")]
        public AfterDecimal AfterDecimal { get; set; }

        [JsonProperty("locale")]
        public string Locale { get; set; }
    }

    public partial class AfterDecimal
    {
        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("words")]
        public string[] Words { get; set; }

        [JsonProperty("numberOfDigits_numeric")]
        public long NumberOfDigitsNumeric { get; set; }

        [JsonProperty("numberOfDigits_words")]
        public string NumberOfDigitsWords { get; set; }
    }
}
